[SETTING/#8] Security 및 OpenFeign 설정
sopt-makers/sopt-auth-backend-legacy pull request #11
Opened 2024-10-08 12:07 UTC by yummygyudon

## Related Issue 🚀
- closed #8 

## Work Description ✏️
- Spring Clouf OpenFeign 기본 설정
- Spring Security 기본 설정

## PR Point 📸

### JwtProvider 추상화
> 4b6daba47217a04cd2a8ed86ac24b72ab3680c72

우선 인증 Jwt 정책에 대한 구현은 @hyunw9 님이 담당하기로 하여 인터페이스로 추상화하여 행위만 정의한 후,
`AuthenticationJwtProvider` 객체를 선언한 해놓은 상태입니다!!

**[Provider를 추상화하여 분리한 이유]**
- Jwt는 "인증"외 다른 관심사에서도 사용할 가능성이 높다고 생각을 했습니다. 이에 행위까지만 정의 & Generic을 통해 Provider의 관심사를 명시할 수 있도록 했습니다.
- 모든 Provider는 같은 행위를 수행할 수 있도록 강제할 수 있습니다.

<br/>

### OpenFeign Retry 제외
> c0b787f06400a7b662b288ec7116aeb0d4457ade

구현까지 완료하였으나 (조금 아깝긴 하네요...ㅠㅜ)
현재 인증 서버 분리 프로젝트에서 분명히 필요한 상황이 아니기 때문에 오버 엔지니어링이라고 판단하여 제외했습니다.

추후에 어플리케이션 안정성 측면에서 Retry 정책이 필요하게 된다면 추가하도록 하겠습니다.

<br/>

### 설정값(`.yml` / `.properties`) 관리 객체 
> 129f93e24776fb63bd372cbba8a890f888097f60

설정파일의 값을 객체로 바인딩하여 사용하는 방법은 상당히 다양합니다.
이 중 java 17 이상의 버전을 쓰는만큼 최대한 제공하는 API를 활용하고자 `Record` 타입으로 객체를 사용하고자 했습니다.

**[Record & `@ConfigurationProperties`를 사용한 이유]**
- 값이 매우 많을 경우, 모든 필드마다 `@Value` 어노테이션을 함께 등록해주는 비효율성 개선
- 불변성 보장 (Record 타입)
  - 기존에 불변성 보장을 위해선 일반 class에 `@ConstructorBinding` & `@RequiredArgsConstructor`이 필요했지만 이제 필요 없음
- inner Record를 통해 그룹핑 용이 (`@NestedConfigurationProperty` 사용 안해도 가능)
- `@ConfigurationProperties`이 지원하는 RelaxedBinding이 적용되어 보다 유연하게 값 바인딩 가능

**※ 단, 설정파일의 Key값과 매핑되기 때문에 field의 이름은 key이름과 통일해야 합니다**
**※ 단, Spring Application 클래스가 위치한 모듈에서도 해당 모듈만의 설정 파일이 있기 때문에 `@EnableConfigurationProperties` 명시가 필요합니다.**

2024-10-08 13:33 UTC, hyunw9 reviewed
코드 한번 훑으면서 궁금한점 먼저 우선적으로 작성해보았습니다.. ! 답변 달아주시면 감사하겠습니다..! 

이건 개인적인 제안인데, 상수타입을 Const -> Constant로 변경하는건 어떨지 제안드립니다 ! 

정말 사소할 수 있는데, 개인적으로 더 잘 읽히는 느낌이긴 한 것 같아서요.. (Req, Res -> Response 의 느낌..? )

2024-10-08 13:33 UTC, hyunw9 commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/BearerAuthRequestInterceptor.java
> +    public abstract void apply(RequestTemplate template);
해당 interceptor 와 apply의 용도가 뭔지 여쭤봐도 될까요 ? 

feign으로 수신한 토큰에 대한 파싱을 인터셉트 하는 용도일까요 ? ? ?

2024-10-08 13:33 UTC, hyunw9 commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/ClientProperty.java
> +    Playground playground
이 부분은 PlaygroundProperty를 Record 타입으로 주입받아서 사용하는 부분일까요 ??

2024-10-08 13:33 UTC, hyunw9 commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/ClientProperty.java
> +    Playground playground
맞군요 ! 그렇다면 해당 프로퍼티는 플그쪽에 토큰값(인증여부) 반환을 위한 프로퍼티일까요 ?

2024-10-08 20:22 UTC, yummygyudon commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/ClientProperty.java
> +    Playground playground
기존 operation 프로젝트에서 사용하던 `ValueConfig.class`와 동일한 설정값 객체에용!!!
참고로 `@ConfigurationProperties` 어노테이션이 설정 파일을 읽어와 값을 Binding해주는 친구입니다.

그래서 아래 두 개의 객체는 동일하게 값을 가지게 된다고 생각하시면 됩니다!!
이렇게 적용한 이유는 PR 본문에 적어두었구요!!
```java
public class ValueConfig {
    
    @Value("${external.sopt-makers.playground.url}")
    private String playgroundUrl;
    ...

}

@ConfigurationProperties("external.sopt-makers")
public record ClientProperty(
    Playground playground
){
    public record Playground(
        String url
    ) {
    }
}
public 
```

2024-10-08 20:24 UTC, yummygyudon commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/BearerAuthRequestInterceptor.java
> +    public abstract void apply(RequestTemplate template);
RequestInterceptor 라는 이름처럼
Feign -> 외부 서버로 요청할 때, 요청 전에 Intercept해 본 Config 설정파일을 활용하는 Client의 요청엔 공통적으로 주입되도록 한거에요!!

Playground Token이 헤더에 항상 주입되어야 하니 위와 같이 Interceptor를 활용하여
자칫 Client 인터페이스 내 Feign 메서드마다 반복될 수 있는 헤더 주입 코드 작성을 방지했습니다!!

2024-10-08 20:25 UTC, yummygyudon commented
> 상수타입을 Const -> Constant로 변경하는건 어떨지 제안드립니다 !

동의합니다!! 리뷰 달아주시는대로 바로 반영하여 Commit 하겠습니다!

2024-10-09 04:05 UTC, sung-silver requested changes
저번주 final 키워드 붙이기로 한 내용이 전반적으로 반영되어있지 않은 것 같아서 확인 부탁드립니다!
저번주에 논의했던 내용 중 대부분을 구현해주셔서 너무 감사합니다 🥹

2024-10-09 04:05 UTC, sung-silver commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/BearerAuthRequestInterceptor.java
> +    public BearerAuthRequestInterceptor(String token) {
P1: 생성자 파라미터에 final 키워드 반영 부탁드립니다!

2024-10-09 04:05 UTC, sung-silver commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/BearerAuthRequestInterceptor.java
> +    public abstract void apply(RequestTemplate template);
P1: 메서드 파라미터에 final 키워드 반영 부탁드립니다!

2024-10-09 04:05 UTC, sung-silver commented on support/src/main/java/sopt/makers/authentication/support/system/security/filter/JwtAuthenticationFilter.java
> +        return request.getHeader(HttpHeaders.AUTHORIZATION).substring(HttpHeaders.AUTHORIZATION.length()).trim();
P5: return하는 값에 대해서 설명적 변수로 한번 명시하고 return해주면 리팩터링 과정에서 trim 메서드를 지운다던가 등의 실수를 줄일 수 있을 것 같은데 어떻게 생각하시나요?

2024-10-09 04:17 UTC, hyunw9 commented on infra/src/main/java/sopt/makers/authentication/infra/client/openfeign/config/BearerAuthRequestInterceptor.java
> +    public abstract void apply(RequestTemplate template);
확인했습니다 !

2024-10-09 04:19 UTC, hyunw9 requested changes
Const -> Constant 수정 요청

2024-10-09 04:19 UTC, hyunw9 commented on support/src/main/java/sopt/makers/authentication/support/value/SystemConst.java
> +public final class SystemConst {
Const -> Constant 수정 요청입니다 !

2024-10-09 04:19 UTC, hyunw9 commented on infra/src/main/java/sopt/makers/authentication/infra/value/ClientConst.java
> +public final class ClientConst {
Const -> Constant 수정 요청입니다 !

2024-10-10 07:14 UTC, yummygyudon commented on support/src/main/java/sopt/makers/authentication/support/system/security/filter/JwtAuthenticationFilter.java
> +        return request.getHeader(HttpHeaders.AUTHORIZATION).substring(HttpHeaders.AUTHORIZATION.length()).trim();
한 줄로 처리하지 않고 `getHeader().substring()` 과 `trim()`을 분리하자는 말씀이시죠?!!
좋습니다!!

2024-10-10 07:55 UTC, sung-silver commented on support/src/main/java/sopt/makers/authentication/support/system/security/filter/JwtAuthenticationFilter.java
> +        return request.getHeader(HttpHeaders.AUTHORIZATION).substring(HttpHeaders.AUTHORIZATION.length()).trim();
```
String authorizationTokenFromHeader = request.getHeader(HttpHeaders.AUTHORIZATION).substring(HttpHeaders.AUTHORIZATION.length()));
String authorizationToken = authorizationTokenFromHeader.trim()
return authorizationToken
```

이런식으로 설명적 변수로 분리하는 것을 말씀드린겁니다!
trim을 분리하자는 말씀이신 것 같아서 분리해서 적어두긴했는데 한줄로 처리하고 trim까지 진행해야 토큰을 얻는다~는 느낌으로 가도 될 것 같네요!

2024-10-10 11:03 UTC, hyunw9 approved these changes

2024-10-10 12:12 UTC, sung-silver approved these changes
진짜 고생하셨습니다~

2024-10-10 12:43 UTC, merged